import type { ActivityEvent, Item, MatchCase } from "./types";

const d = (iso: string) => iso;

export const SEED_ITEMS: Item[] = [
  {
    id: "item-lost-wallet",
    type: "LOST",
    title: "Black Leather Wallet",
    category: "Wallet",
    description: "Black leather wallet with college ID and two debit cards inside.",
    location: "CS Block",
    date: d("2026-08-27"),
    contactName: "Aarav Menon",
    contactInfo: "aarav.m@campus.edu",
    status: "MATCHED",
    createdAt: "2026-08-27T09:20:00.000Z",
  },
  {
    id: "item-found-wallet",
    type: "FOUND",
    title: "Black Wallet",
    category: "Wallet",
    description: "Found a black leather wallet near the CS Block staircase.",
    location: "CS Block",
    date: d("2026-08-27"),
    contactName: "Priya Nair",
    contactInfo: "priya.n@campus.edu",
    status: "MATCHED",
    createdAt: "2026-08-27T14:05:00.000Z",
  },
  {
    id: "item-lost-id",
    type: "LOST",
    title: "Blue Student ID Card",
    category: "ID Card",
    description: "Blue student ID card, batch 2024, lanyard attached.",
    location: "Library",
    date: d("2026-08-26"),
    contactName: "Rohit Sharma",
    contactInfo: "9876543210",
    status: "MATCHED",
    createdAt: "2026-08-26T11:00:00.000Z",
  },
  {
    id: "item-found-id",
    type: "FOUND",
    title: "Blue ID Card",
    category: "ID Card",
    description: "Blue ID card found on the Library reading desk, second floor.",
    location: "Library",
    date: d("2026-08-26"),
    contactName: "Sneha Iyer",
    contactInfo: "sneha.i@campus.edu",
    status: "MATCHED",
    createdAt: "2026-08-26T17:40:00.000Z",
  },
  {
    id: "item-lost-airpods",
    type: "LOST",
    title: "AirPods Pro",
    category: "Earphones",
    description: "White AirPods Pro case with a small blue sticker on the back.",
    location: "Auditorium",
    date: d("2026-08-28"),
    contactName: "Kabir Rao",
    contactInfo: "kabir.r@campus.edu",
    status: "OPEN",
    createdAt: "2026-08-28T08:15:00.000Z",
  },
  {
    id: "item-found-flask",
    type: "FOUND",
    title: "Hydro Flask Bottle",
    category: "Water Bottle",
    description: "Matte green Hydro Flask bottle left near the basketball court bench.",
    location: "Sports Complex",
    date: d("2026-08-28"),
    contactName: "Meera Das",
    contactInfo: "meera.d@campus.edu",
    status: "OPEN",
    createdAt: "2026-08-28T18:30:00.000Z",
  },
];

export const SEED_MATCHES: MatchCase[] = [
  {
    id: "case-wallet",
    lostItemId: "item-lost-wallet",
    foundItemId: "item-found-wallet",
    matchScore: 92,
    status: "POSSIBLE",
    createdAt: "2026-08-27T14:06:00.000Z",
  },
  {
    id: "case-id",
    lostItemId: "item-lost-id",
    foundItemId: "item-found-id",
    matchScore: 88,
    status: "POSSIBLE",
    createdAt: "2026-08-26T17:41:00.000Z",
  },
];

export const SEED_ACTIVITY: ActivityEvent[] = [
  {
    id: "act-1",
    kind: "MATCH",
    message: "Smart match found: Black Leather Wallet ⟷ Black Wallet (92%)",
    at: "2026-08-27T14:06:00.000Z",
  },
  {
    id: "act-2",
    kind: "REPORT",
    message: "Found item reported: Hydro Flask Bottle at Sports Complex",
    at: "2026-08-28T18:30:00.000Z",
  },
  {
    id: "act-3",
    kind: "REPORT",
    message: "Lost item reported: AirPods Pro at Auditorium",
    at: "2026-08-28T08:15:00.000Z",
  },
  {
    id: "act-4",
    kind: "MATCH",
    message: "Smart match found: Blue Student ID Card ⟷ Blue ID Card (88%)",
    at: "2026-08-26T17:41:00.000Z",
  },
];
